### ISSUE TITLE
Cryofluid Bug

### ISSUE THREAD

**Issue by Humanoid-X** [genNAowl/Upgraded-Factories#1]
When I load the mod, it says this:

```
              An error has ocurred
     -------------------------------------
Errors have occured while loading content
upgraded-factories
----------------------------------------------
cryofluidblender    ̌    Details...
```

When I opened Details... 

```
File: cryofluidblender.json
[IllegalArgument] Content "cryofluidmixer" isn't in the tech tree, but "upgraded-factories-crofluidblender" requires it to be researched.
```

So I looked at the Mindustry official TechTree.java and changed `cryofluidmixer` to `cryofluidMixer`...
And the same error showed up, except changing the `cryofluidmixer`'s name.

What is happening?!

**Comment by genNAowl** [comment]
Yeah that is due to the name of "cryofluidmixer" changing to "cryofluid-mixer" 

I fixed it in the newer versions of the mod, but the version you downloaded is probably not up to date.

**Comment by genNAowl** [comment]
To fix, simply download a newer version of the mod

**Comment by Humanoid-X** [comment]
Wow thanks :-D
