### ISSUE TITLE
Unnecessary assets packaged with JAR

### ISSUE THREAD

**Issue by Anuken** [genNAowl/Upgraded-Factories#12]
![image](https://user-images.githubusercontent.com/10100000/122841084-6cc45e00-d2c9-11eb-94e7-f8ccbe2007eb.png)

The `assets/` folder includes GitHub README images, which aren't used in the actual mod and increase JAR download size from <1mb to 19+. This isn't particularly significant for PCs with a good internet connection, but on mobile devices with data caps and low storage space, it makes a noticeable difference. Proposed solution: Move the files into a different folder.

*(If you're wondering why I'm here, it's because GitHub suggested me this repo and I was slightly bored)*

**Comment by genNAowl** [comment]
Moved the README images from `assets` to a `demos` folder. 

Dang it's weird seeing Anuken on a random repo like this.
