### ISSUE TITLE
More buildings ideas

### ISSUE THREAD

**Issue by DatOnePlayer** [genNAowl/Upgraded-Factories#3]
Possibly like upgraded water extractor, or even power sources? Or even upgraded oil extractor

**Comment by genNAowl** [comment]
> upgraded water extractor and upgraded oil extractor

Already in the source code; I just have not fully implemented them because I don't see a need for them yet. 

> power sources

Its on my mind, but since I'm pretty inactive now, don't bet on it

**Comment by genNAowl** [comment]
I have now added an upgraded oil/water extractor

![Better Extractors](https://user-images.githubusercontent.com/68400583/113240891-74dca680-9262-11eb-92d7-99be7a21585b.jpg)
