### ISSUE TITLE
can't import mod on mobile

### ISSUE THREAD

**Issue by LenLukSVK** [genNAowl/Upgraded-Factories#6]
Hi I'm really excited to play your mod but I can't import it on mobile. Didn't try it on PC though. When I try the mod browser option it says error with upgraded factories. Import file option says with zip that there isn't a json file and and unzipped wants to open individual folders. Got hub import says the same error as mod browser. Id like to know how to fix it of you know. Thanks a lot. I'll be happy to play your mod.

**Comment by genNAowl** [comment]
Sorry for that, I just realized I need to dex the jar file.

**Comment by genNAowl** [comment]
Yo try running this: https://github.com/genNAowl/Upgraded-Factories/releases/tag/2.1

If it works, close the issue

**Comment by LenLukSVK** [comment]
I'm sorry it still doesn't work the jar file says error:UpgradedFactories and zip file says there is no json file. I'm sorry hope you will fix it someday. I wish you good luck :)

**Comment by LenLukSVK** [comment]
It works!!!!! Not through import file but trough mod browser!!!! Thank you very much !!!!!! :D
