### ISSUE TITLE
Can't import on android

### ISSUE THREAD

**Issue by oguh43** [genNAowl/Upgraded-Factories#7]
Version: 6-official-126.2
Error: upgraded.UpgradedFactories
Android: 11
Samsung

**Comment by oguh43** [comment]
![Screenshot_20210604-085724_Mindustry](https://user-images.githubusercontent.com/13382592/120759098-eeb73780-c512-11eb-9b2d-bbef9b4b9d17.png)
![Screenshot_20210604-085720_Mindustry](https://user-images.githubusercontent.com/13382592/120759100-f080fb00-c512-11eb-8b50-ca003544089b.png)
![Screenshot_20210604-085712_Mindustry](https://user-images.githubusercontent.com/13382592/120759105-f1b22800-c512-11eb-86bb-6d352feab749.png)

**Comment by genNAowl** [comment]
That's my bad; I haven't dexified the jar file. I'll try to do that, but for some reason, I can't get it to work on my computer.

**Comment by genNAowl** [comment]
Yo try running this: https://github.com/genNAowl/Upgraded-Factories/releases/tag/2.1

If it works, close the issue

**Comment by genNAowl** [comment]
The person who created the issue https://github.com/genNAowl/Upgraded-Factories/issues/6 says it works on mobile now; Gonna assume it's the same for you.

**Comment by oguh43** [comment]
After testing, it works great :)
