### ISSUE TITLE
unable to import on pc via mod menu(steam version)

### ISSUE THREAD

**Issue by TheBlueTroll** [genNAowl/Upgraded-Factories#8]
When trying to install via the in-game mod menu, i run into a error when importing:

IO: 'java.lang.UnsupportedClassVersionError: upgraded/UpgradedFactories has been compiled by a more recent version of the Java Runtime (class file version 59.0), this version of the Java Runtime only recognizes class file versions up to 52.0)

this is a issue because when steam installs Mindustry, it includes java 8, and you compiled the mod with java 15. 
this means to run the mod i would have to go and get the itch,io version and install java 15 at least manually, which can be very hard for non tech literate players to do. which people on steam can be.

edit: added screenshot of error
![Screenshot (2)](https://user-images.githubusercontent.com/9428136/120885023-f9b0bb80-c629-11eb-925a-7285da0df57d.png)

**Comment by genNAowl** [comment]
Hmm I'm not exactly sure how to change which java version I'm compiling this on. 

I'll try to look into it.

**Comment by TheBlueTroll** [comment]
as a update to this, mindustry v7 Pre-Alpha launch on steam is now moving to java 16 , soo problem fixed, thanks for the mod ;)

sauce: https://store.steampowered.com/news/app/1127400/view/2978550342264439407

specifically the line : "Updated packaged Java version to 16"

**Comment by genNAowl** [comment]
Noice

Does that mean I can close?

**Comment by TheBlueTroll** [comment]
I dont see why not.
